#===============================================================================
# User Options
#===============================================================================

# Compiler can be set below, or via environment variable
CC        = clang++
OPTIMIZE  = yes
DEBUG     = no
LAUNCHER  =

GPU       = yes
CUDA      = no
CUDA_ARCH = sm_70
HIP       = no
HIP_ARCH  = gfx908
GCC_TOOLCHAIN = "/auto/software/gcc/x86_64/gcc-9.1.0/"

#===============================================================================
# Program name & source code list
#===============================================================================

program = main

source = kernel.cpp fim.cpp timer.cpp main.cpp StructuredEikonal.cpp

obj = kernel.o fim.o timer.o main.o StructuredEikonal.o

#===============================================================================
# Sets Flags
#===============================================================================

# Standard Flags
CFLAGS := $(EXTRA_CFLAGS) -std=c++17 -Wall -I../eikonal-cuda -fsycl

# Linker Flags
LDFLAGS = 

ifeq ($(CUDA), yes)
  CFLAGS += -fsycl-targets=nvptx64-nvidia-cuda \
            -Xsycl-target-backend --cuda-gpu-arch=$(CUDA_ARCH) \
            --gcc-toolchain=$(GCC_TOOLCHAIN)
endif

ifeq ($(HIP), yes)
  CFLAGS += -fsycl-targets=amdgcn-amd-amdhsa \
	    -Xsycl-target-backend --offload-arch=$(HIP_ARCH) 
endif

# Debug Flags
ifeq ($(DEBUG),yes)
  CFLAGS += -g -DDEBUG
  LDFLAGS  += -g
endif

# Optimization Flags
ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3
endif

ifeq ($(GPU),yes)
  CFLAGS +=-DUSE_GPU
endif
#===============================================================================
# Targets to Build
#===============================================================================

$(program): $(obj)
	$(CC) $(CFLAGS) $(obj) -o $@ $(LDFLAGS)

kernel.o: kernel.cpp kernel.h
	$(CC) $(CFLAGS) -c $< -o $@

fim.o: fim.cpp fim.h kernel.h
	$(CC) $(CFLAGS) -c $< -o $@

timer.o : ../eikonal-cuda/timer.cpp ../eikonal-cuda/timer.h ../eikonal-cuda/my_exception.h
	$(CC) $(CFLAGS) -c $< -o $@

StructuredEikonal.o : StructuredEikonal.cpp StructuredEikonal.h common_def.h
	$(CC) $(CFLAGS) -c $< -o $@

main.o : main.cpp StructuredEikonal.h
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(program) $(obj) output.nrrd

run: $(program)
	$(LAUNCHER) ./$(program) -s 512
