all:
	(cd lib; make)
	(cd util; make)
	(cd demo; make)

lib:
	(cd lib; make)

util:
	(cd util; make)

demo:
	(cd demo; make)

clean:
	(cd lib; make clean)
	(cd util; make clean)
	(cd demo; make clean)
